apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: 968225077300.dkr.ecr.us-west-1.amazonaws.com/devops-na-nuvem/production/frontend:v1.0
          ports:
            - containerPort: 80
